creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - age1fnle7w46h40zap4efs52lczmt47zg0h5waml3r3jmqgtkwdxep0q89wz27
          - age1gmfqleddjg8x6mllz8z6jgkrll8azcwnxv97zkshlh9y5jzqry7qe3dg0v
