# Autostart applications
exec-once = swaybg -i /home/sintra/nixos/wallpapers/tokyonight.png -m fill
exec-once = waybar
exec-once = mako
exec-once = [workspace 2] firefox
exec-once = [workspace 3] ghostty -e yazi
exec-once = [workspace 4] ghostty -e verso
exec-once = [workspace 5] ghostty -e rqbit
exec-once = [workspace 6] ghostty -e btm
exec-once = [workspace 6] ghostty -e pulsemixer
exec-once = [workspace 7] vesktop
exec-once = [workspace 7] signal-desktop
exec-once = [workspace 8] ghostty -e aerc
exec-once = [workspace 9] ghostty -e musikcube
exec-once = [workspace 10] ghostty -e hermes
