# Autostart applications
exec-once = swaybg -i /home/sintra/nixos/wallpapers/tokyonight.png -m fill
exec-once = waybar
exec-once = mako
exec-once = [workspace 2] zen
exec-once = [workspace 3] ghostty -e yazi
exec-once = [workspace 4] ghostty -e verso
exec-once = [workspace 6] ghostty -e podman-tui
exec-once = [workspace 7] ghostty -e btm
exec-once = [workspace 8] ghostty -e aerc
exec-once = [workspace 9] ghostty -e nu -c "sleep 3sec; musikcube"
exec-once = [workspace 10] ghostty -e hermes
