# Autostart applications
exec-once = swaybg -i /home/sintra/nixos/wallpapers/tokyonight.png -m fill
exec-once = waybar
exec-once = mako
exec-once = [workspace 2] zen
exec-once = [workspace 3] sh -c 'while [ ! -S "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; do sleep 0.1; done; exec footclient -a foot-yazi yazi'
exec-once = [workspace 4] sh -c 'while [ ! -S "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; do sleep 0.1; done; exec footclient -a foot-verso verso'
exec-once = [workspace 6] sh -c 'while [ ! -S "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; do sleep 0.1; done; exec footclient -a foot-podman podman-tui'
exec-once = [workspace 7] sh -c 'while [ ! -S "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; do sleep 0.1; done; exec footclient -a foot-btm btm'
exec-once = [workspace 8] sh -c 'while [ ! -S "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; do sleep 0.1; done; exec footclient -a foot-aerc aerc'
exec-once = [workspace 9] sh -c 'while [ ! -S "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; do sleep 0.1; done; exec footclient -a foot-musikcube nu -c "sleep 3sec; musikcube"'
exec-once = [workspace 10] sh -c 'while [ ! -S "$XDG_RUNTIME_DIR/foot-$WAYLAND_DISPLAY.sock" ]; do sleep 0.1; done; exec footclient -a foot-hermes hermes'
